---
permalink: rhel-install/task-create-a-certificate-signing-request-for-workflow-automation-linux.html 
sidebar: sidebar 
keywords: workflow automation, wfa, linux, create, signing, request 
summary: Linux で証明書署名要求（ CSR ）を作成すると、 Workflow Automation （ WFA ）のデフォルトの SSL 証明書ではなく、認証局（ CA ）が署名した SSL 証明書を使用できるようになります。 
---
= Workflow Automation の証明書署名要求を作成します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux で証明書署名要求（ CSR ）を作成すると、 Workflow Automation （ WFA ）のデフォルトの SSL 証明書ではなく、認証局（ CA ）が署名した SSL 証明書を使用できるようになります。

.必要なもの
* WFA をインストールした Linux システムに対する root 権限が必要です。
* WFA のデフォルトの SSL 証明書を置き換えておく必要があります。


.このタスクについて
WFA のデフォルトのインストールパスは、この手順 で使用されます。インストール時にデフォルトパスを変更した場合は、カスタムの WFA インストールパスを使用する必要があります。

.手順
. WFA ホストマシンに root ユーザとしてログインします。
. WFA サーバでシェルプロンプトを開き、ディレクトリを次の場所に変更します。
+
wfa_install_location /wfa/jre/bin

. CSR ファイルを作成します。
+
keytool -certreq -keystore wfa_install_location WFA/jboss/standalone/configuration /keystore/wfa_keystore -alias "ssl keystore" -file /root/file_name .csr`

+
_file_name _ は CSR ファイルの名前です。

. プロンプトが表示されたら、パスワードを入力します（デフォルトまたは新規）。
+
* changeit * はデフォルトのパスワードです。デフォルトのパスワードを使用しない場合は、「 wfa_install_location /wfa/jboss/standalone/configuration 」の場所から「 standalone-full.xml 」ファイル内の SSL 要素のパスワード属性を変更する必要があります。

+
* 例 *

+
[listing]
----
<ssl name="ssl" password="new_password" certificate-key-file="${jboss.server.config.dir}/keystore/wfa.keystore"
----
. 署名済み証明書を取得するために、 _file_name .csr_ ファイルを CA に送信します。
+
詳細については、 CA の Web サイトを参照してください。

. CA からチェーン証明書をダウンロードし、チェーン証明書をキーストアにインポートします。
+
keytool -import -alias "ssl keystore wfa_install_location /wfa/standalone/configuration /keystore.keystore" -trustcacerts-file C ： \chain_cert.cer

+
C:\chain_cert.cer' は 'CA から受信したチェーン証明書ファイルですファイルは X.509 形式である必要があります。

. CA から受け取った署名付き証明書をインポートします。 keytool -import -alias "ssl keystore" -keystore wfa_install_location /wfa/standalone/configuration /keystore.keystore "-trustcacerts-file C:\certificate.cer
+
「 C:\certificate.cer 」は、 CA から受信したチェーン証明書ファイルです。

. WFA のサービスを開始します。
+
`./wfa -- start=db`

+
`./wfa -- start=wfa


