---
permalink: rhel-install/task-upgrade-from-wfa-4-2.html 
sidebar: sidebar 
keywords: oncommand workflow automation, upgrade, 3.1 or later 
summary: OnCommand Workflow Automation （ WFA ） 3.1 以降から WFA の最新バージョンへのインプレースアップグレードを実行して、新しい機能と拡張機能を使用できます。 
---
= OnCommand Workflow Automation 3.1 以降からアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ） 3.1 以降から WFA の最新バージョンへのインプレースアップグレードを実行して、新しい機能と拡張機能を使用できます。

ネットアップサポートサイトから WFA ホストマシンに .bin バイナリファイルをダウンロードしておく必要があります。

WFA 5.0 へのリストアは、 WFA 4.2 または 4.1 からのみ実行できます。WFA のデータベースバックアップは、同じバージョンかそれ以降のバージョンの WFA を実行しているシステムにのみリストアできます。

以前のバージョンの WFA からアップグレードする場合、 MySQL を独自にインストールすることはできません。MySQL は独自にインストールできます。

* WFA 4.2 から新しいバージョンの WFA にアップグレードする場合。
* 次のいずれかの方法を選択して WFA 3.1 以降からアップグレードします。
+
** 対話型インストール
+
... WFA ホストマシンのバイナリファイル「 .bin 」に移動して、ファイルを実行します。
... 画面に表示される手順に従って、アップグレードを完了します。


** サイレントインストール
+
シェルプロンプトで、次のように入力します

+
WFA-version_number-build_number.bin [-y] [-u admin_user_name [-p admin_user_password]

+
* 例： *

+
WFA-3.1-Z3234343435.bin -y -u admin -p Company * 234`

+
サイレントアップグレードでは、次のすべてのコマンドオプションの値を含める必要があります。

+
*** 「 -y 」を指定すると、インストールの確認が省略されます。
*** 「 -u 」は、 admin ユーザ名を指定します。
*** `-p` は admin ユーザのパスワードを指定する。
+
admin ユーザのパスワードを指定していない場合は、プロンプトが表示されたらパスワードを入力する必要があります。






