---
permalink: windows-install/reference-system-requirements-for-oncommand-workflow-automation-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, system, requirements, install 
summary: WFA をインストールする前に、 OnCommand Workflow Automation （ WFA ）のハードウェアとソフトウェアの要件を理解しておく必要があります。 
---
= OnCommand Workflow Automation をインストールするためのシステム要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA をインストールする前に、 OnCommand Workflow Automation （ WFA ）のハードウェアとソフトウェアの要件を理解しておく必要があります。



== WFA をインストールするためのハードウェア要件

次の表に、 WFA サーバのハードウェアの最小要件と推奨されるハードウェア仕様を示します。

[cols="3*"]
|===
| コンポーネント | 最小要件 | 推奨される仕様 


 a| 
CPU
 a| 
2.27GHz 以上、 2 コア、 64 ビット
 a| 
2.27GHz 以上、 2 コア、 64 ビット



 a| 
RAM
 a| 
4 GB
 a| 
8 GB



 a| 
空きディスク容量
 a| 
5 GB
 a| 
20 GB

|===
WFA を仮想マシン（ VM ）にインストールする場合は、 VM に十分なリソースが確保されるように、必要なメモリと CPU を確保しておく必要があります。インストーラは CPU 速度を確認しません。



== WFA をインストールするためのソフトウェア要件

WFA は 64 ビットの Windows オペレーティングシステムで実行され、専用の物理マシンまたは VM にインストールする必要があります。WFA を実行するサーバには、他のアプリケーションをインストールしないでください。

WFA は、 Microsoft Windows Server 2012 Enterprise Edition から Microsoft Windows Server 2016 （すべてのエディション）に実行されます。Enterprise Edition は、推奨される Windows オペレーティングシステムです。

* その他の最低限必要なソフトウェア *

* 次のいずれかのブラウザがサポートされています。
+
** Mozilla Firefox
** Microsoft Internet Explorer の略
** Google Chrome


* ブラウザの Adobe Flash Player の最新バージョン
* PowerShell 3.0
* VMware PowerCLI バージョン 5
+

NOTE: VMware API 用の PowerShell 拡張機能が必要になるのは、 WFA を使用して VMware vSphere 上でワークフローを実行する場合のみです。



詳細については、を参照してください https://mysupport.netapp.com/matrix["Interoperability Matrix Tool で確認してください"^]。
