---
permalink: windows-install/task-back-up-regular-the-wfa-database-using-perl-script-linux.html 
sidebar: sidebar 
keywords: ocommand workflow automation, back up, wfa, database cli 
summary: OnCommand Workflow Automation （ WFA ）データベースの定期バックアップは、 WFA コマンドラインインターフェイス（ CLI ）を使用して実行できます。通常のバックアップでは、 WFA データベースのみがバックアップされます。 
---
= CLI を使用して WFA データベースを（通常の）バックアップします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation （ WFA ）データベースの定期バックアップは、 WFA コマンドラインインターフェイス（ CLI ）を使用して実行できます。通常のバックアップでは、 WFA データベースのみがバックアップされます。

.必要なもの
管理者ユーザクレデンシャル、アーキテクトクレデンシャル、またはバックアップユーザクレデンシャルが必要です。

.このタスクについて
ハイアベイラビリティ環境では、 REST API を使用してスケジュールされたバックアップを作成する必要があります。WFA がフェイルオーバーモードの場合、 CLI を使用してバックアップを作成することはできません。

詳細については、 REST のドキュメントを参照してください。

.手順
. シェルプロンプトで、 WFA サーバの次のディレクトリに移動します。
+
wfa_install_location WFA\bin

+
「 wfa_install_location 」は WFA のインストールディレクトリです。

. WFA データベースをバックアップします。
+
`..\wfa --backup --user=user [--password=pass][--location=path]'

+
** _user_は 、バックアップユーザのユーザ名です。
** _password_ はバックアップユーザのパスワードです。


+
パスワードを指定していない場合は、プロンプトが表示されたらパスワードを入力する必要があります。

+
** _path _ は、バックアップファイルへの完全なディレクトリパスです。


. * オプション： * 指定した場所にバックアップファイルが作成されたことを確認します。

