---
permalink: windows-install/task-upgrade-oncommand-workflow-automation.html 
sidebar: sidebar 
keywords: upgrade, oncommand, workflow, automation 
summary: 以前のバージョンの OnCommand Workflow Automation （ WFA ）がインストールされている場合は、新しい機能と機能拡張を使用するために最新バージョンの WFA にアップグレードできます。 
---
= OnCommand Workflow Automation をアップグレードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以前のバージョンの OnCommand Workflow Automation （ WFA ）がインストールされている場合は、新しい機能と機能拡張を使用するために最新バージョンの WFA にアップグレードできます。

.このタスクについて
* WFA 5.0 へのアップグレードは、 WFA 4.2 または 4.1 からのみ実行できます。
+
現在 WFA 4.0 以前のバージョンの WFA を実行している場合は、まず WFA 4.2 または 4.1 にアップグレードしてから、 WFA 5.0 にアップグレードする必要があります。

* WFA 5.0 では、 WFA 4.1 または 4.2 で作成されたバックアップをリストアできます。WFA のデータベースバックアップは、同じバージョンかそれ以降のバージョンの WFA を実行しているシステムにのみリストアできます。
+
たとえば、 WFA 4.2 を実行しているシステムで作成したバックアップは、 WFA 4.2 以降を実行しているシステムにのみリストアできます。

* WFA 4.2 より前のバージョンからアップグレードする場合は、 MySQL を独自にインストールすることはできません。
+
ただし、 MySQL は独自にインストールできます。

+
** WFA 4.2 以降を新規にインストールするとき
** WFA 4.2 から新しいバージョンの WFA にアップグレードする場合。




.手順
. 次のいずれかのオプションを使用して WFA データベースをバックアップします。
+
** WFA Web ポータルにアクセスします
** PowerShell スクリプト WFA を同じバージョンにリバートする場合は、作成したバックアップを使用して WFA データベースをリストアできます。


. 既存のバージョンの WFA をアンインストールします。
. 最新バージョンの WFA をインストールします。
. WFA データベースをリストアします。


* 終了後 *

復元されたコンテンツの機能の完全性を確認できます。たとえば、カスタムワークフローの機能を確認できます。
