---
permalink: windows-install/task-configure-a-database-user-by-running-ocsetup-on-linux.html 
sidebar: sidebar 
keywords: configure, database, user, running, ocsetup, linux 
summary: Active IQ Data Center Manager サーバで ocsetup ファイルを実行して、 Active IQ Data Center Manager データベースの OnCommand Workflow Automation への読み取り専用アクセスを設定できます。 
---
= Linux で ocsetup を実行してデータベースユーザを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Data Center Manager サーバで ocsetup ファイルを実行して、 Active IQ Data Center Manager データベースの OnCommand Workflow Automation への読み取り専用アクセスを設定できます。

.手順
. 端末で次のコマンドを使用して 'wfa_ocsetup.sh ファイルを Active IQ Data Center Manager サーバのホーム・ディレクトリにダウンロードします https://WFA_Server_IP/download/wfa_ocsetup.sh+`[]
+
「 wfa_Server_IP 」は、 WFA サーバの IP アドレス（ IPv4 または IPv6 アドレス）です。

+
WFA にデフォルト以外のポートを指定した場合は、次のようにポート番号を含める必要があります。

+
「 + wget 」と入力します https://wfa_server_ip:port/download/wfa_ocsetup.sh+`[]

+
_port_は 、インストール時に WFA サーバに使用した TCP ポート番号です。

+
IPv6 アドレスを指定する場合は、角かっこで囲む必要があります。

. wfa_ocsetup.sh ファイルを実行可能ファイルに変更するには、端末で次のコマンドを使用します。
+
chmod +x wfa_ocsetup.sh

. ターミナルに次のように入力して、スクリプトを実行します。
+
wfa_ocsetup.sh jre_path

+
_jre_path_ は JRE のパスです。

+
* 例 *

+
/opt/NTAPdfm/java

+
次の出力が端末に表示され、セットアップが完了したことが示されます。

+
[listing]
----
Verifying archive integrity... All good.
Uncompressing WFA OnCommand Setup.....
*** Welcome to OnCommand Setup Utility for Linux ***
    <Help information>
*** Please override the default credentials below ***
Override DB Username [wfa] :
----
. ユーザ名とパスワードを入力して、デフォルトクレデンシャルを上書きします。
+
Active IQ Data Center Manager データベースへのアクセスを許可する新しいデータベースユーザアカウントが作成されます。

+

NOTE: ユーザアカウントを作成しない場合は、デフォルトクレデンシャルが使用されます。セキュリティ上の理由からユーザアカウントを作成する必要があります。

+
次の出力が端末に表示され、セットアップが完了したことが示されます。

+
[listing]
----
***** Start of response from the database *****
>>> Connecting to database
<<< Connected
*** Dropped existing 'wfa' user
=== Created user 'username'
>>> Granting access
<<< Granted access
***** End of response from the database *****
***** End of Setup *****
----

