---
permalink: help/reference-new-data-source-dialog-box.html 
sidebar: sidebar 
keywords: new data source, dialog box 
summary: '[ 新しいデータソース ] ダイアログボックスでは、新しいデータソースを追加できます。' 
---
= [ 新しいデータソース ] ダイアログボックス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
[ 新しいデータソース ] ダイアログボックスでは、新しいデータソースを追加できます。



== データソース構成のプロパティ

* * 名前 *
+
データソースの名前を指定できます。

* * データソースの種類 *
+
OnCommand Unified Manager - 6.0 （ MySQL ）などのデータソースのタイプを選択できます。

+
データソースタイプを選択すると、ポート、スキーム、ユーザ名、パスワード、 間隔（分）フィールドとタイムアウト（秒）フィールドにデータが入力されます。

+

NOTE: OnCommand Unified Manager サーバから OnCommand Workflow Automation （ WFA ）のデータ保護ワークフローを実行する場合は、 OnCommand Unified Manager サーバで WFA をセットアップする必要があります。

+
詳細については、 OnCommand Unified Manager オンラインヘルプを参照してください。

* * ホスト名 *
+
データソースのホスト名または IP アドレス（ IPv4 または IPv6 ）を指定できます。

+

NOTE: OnCommand Unified Manager データソースタイプでは、 IPv6 アドレスはサポートされません。

* * ポート *
+
選択したデータソースタイプに関連付けられているポート番号（ある場合）が表示されます。

+
デフォルトのポートを変更して、データソースに別のポートを指定できます。

* * スキーム *
+
選択したデータソースタイプに関連付けられているスキームが表示されます（ OnCommand Unified Manager の場合は「 cm_storage 」、 MySQL の場合は「 cm_storage 」など）。

+
このプロパティは変更できません。

* * ユーザー名 *
+
選択したデータソースタイプに関連付けられているユーザ名（存在する場合）が表示されます。

+
デフォルトのユーザ名を上書きするには、このデータソースに適切なユーザ名を指定する必要があります。

+
** 6.0 より前のバージョンの OnCommand Unified Manager では、 ocsetup の実行時にデフォルトクレデンシャルの上書きに使用したユーザ名を入力する必要があります。
** OnCommand Unified Manager 6.0 以降では、 OnCommand Unified Manager サーバで作成したデータベースユーザアカウントのユーザ名を入力する必要があります。
** Performance Advisor には、 GlobalRead の最小ロールを持つ OnCommand Unified Manager ユーザのユーザ名を入力する必要があります。


* * パスワード *
+
選択したデータソースのタイプに対応するパスワードを指定できます。

+
このデータソースのユーザ名のデフォルトのパスワードを上書きするには、パスワードを指定する必要があります。

+
** OnCommand Unified Manager 6.0 より前のバージョンでは、 ocsetup の実行時にデフォルトクレデンシャルの上書きに使用したパスワードを入力する必要があります。
** OnCommand Unified Manager 6.0 以降では、 OnCommand Unified Manager サーバで作成したデータベースユーザアカウントのパスワードを入力する必要があります。
** Performance Advisor の場合、 GlobalRead の最小ロールが割り当てられた OnCommand Unified Manager ユーザのパスワードを入力する必要があります。


* * データベース *
* * 間隔（分） *
+
値をクリックし、上下の矢印を使用して間隔（分）を選択できます。

+

NOTE: 間隔をゼロ（ 0 ）に設定すると、自動サンプリングは無効になります。

+
データサンプリングのデフォルトの間隔は次のとおりです。

+
** スクリプトベースのデータソースの種類： 1440 （パフォーマンスと VC ）
** SQL ベースのデータソースのタイプ： 30 （ cm_storage 、 storage 、 cm_performance ）


* * セットアップ手順ガイド * を参照してください
+
セットアップ手順ガイド（ Setup Instruction Guide ）ダイアログボックスを開きます。このダイアログボックスで、データソースを設定するための手順を指定できます。





== コマンドボタン

* * 保存 *
+
設定を保存してダイアログボックスを閉じます。

* * キャンセル *
+
変更がある場合はキャンセルしてダイアログボックスを閉じます。


